-- Switch id generation from application-assigned values to a DB identity column,
-- so ids stay unique across service restarts. START well above any id already
-- inserted by earlier manual/dev testing.
ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10000);
